### ISSUE TITLE
Change MassTransitSourceContext to SourceContext.

### ISSUE THREAD

**Issue by NikGovorov** [CaptiveAire/MassTransit.SerilogIntegration#2]
Hi,

Could we please change MassTransitSourceContext(https://github.com/CaptiveAire/MassTransit.SerilogIntegration/blob/master/src/SerilogLogger.cs#L43)  to SourceContext(https://github.com/serilog/serilog/blob/d97f2b4f6fbd2afe42f3ccebfeef1e431eda239b/src/Serilog/Core/Constants.cs#L27) , otherwise other standard sinks like log4net, NLog etc. don't work:
https://github.com/serilog/serilog-sinks-log4net/blob/master/src/Serilog.Sinks.Log4Net/Sinks/Log4Net/Log4NetSink.cs#L49.

Thanks.

**Comment by Jaben** [comment]
Done. Published v3.0.2 with change.

**Comment by NikGovorov** [comment]
Thanks @Jaben!
